Repository CreativePaperCrew/RollingPaper, pull requests merged in 2024-03, with the labels that each got.

#32 Toast 컴포넌트 및 hooks 추가(이미지 및 폴더 대문자 수정 및 package-lock.json 수정)
  package-lock.json
  src/assets/icons/arrowDown.svg
  src/assets/icons/deleted.svg
  src/assets/icons/emojiPicker.svg
  src/assets/icons/share.svg
  src/assets/icons/toast/close.svg
  src/assets/icons/toast/completed.svg
  src/assets/icons/toast/failed.svg
  src/assets/images/mainImg1.png
  src/assets/images/mainImg2.png
  src/components/Badge/Badge.jsx
  src/components/Badge/BadgeStyle.js
  src/components/EmojiBadge/EmojiBadge.jsx
  src/components/EmojiPicker/EmojiPicker.jsx
  src/components/ReactionDropdown/ReactionDropdown.jsx
  src/components/ServiceHeader/ServiceHeader.jsx
  src/components/ServiceHeader/ServiceHeaderStlyle.js
  src/components/ShareButton/ShareButton.jsx
  src/components/ShareButton/ShareButtonStyle.js
  src/components/TopReactions/TopReactions.jsx
  src/components/common/Header/HeaderStyle.js
  src/components/common/Toast/Toast.jsx
  src/components/common/Toast/ToastStyle.js
  src/hooks/useToast.js
Labels: FEATURE

#34 /post/id 초기 페이지 추가 및 데이터 연동 및 hooks 추가
  src/Router.jsx
  src/apis/recipientRollingPaperApi.js
  src/components/PostCard/PostCard.jsx
  src/components/ServiceHeader/ServiceHeader.jsx
  src/components/ServiceHeader/ServiceHeaderStyle.js
  src/components/ShareButton/ShareButton.jsx
  src/components/TopReactions/TopReactions.jsx
  src/constants/colors.js
  src/hooks/useFetchData.js
  src/pages/PostPage/PostPage.jsx
  src/pages/RecipientsPage/RecipientsPage.jsx
  src/pages/RecipientsPage/RecipientsPageStyle.js
  src/utils/formatKSTDate.js
Labels: FEATURE

#29 PostCreatingPage 생성
  package-lock.json
  package.json
  src/Router.jsx
  src/apis/getBackgroundImages.js
  src/assets/icons/check.svg
  src/components/BackgroundSelector/BackgroundSelector.jsx
  src/components/BackgroundSelector/BackgroundSelectorStyle.js
  src/components/BackgroundTypeSelectButton/BackgroundTypeSelectButton.jsx
  src/components/BackgroundTypeSelectButton/BackgroundTypeSelectButtonStyle.js
  src/components/Input/Input.jsx
  src/components/Input/InputStyle.js
  src/components/common/Buttons/LinkButton/LinkButton.jsx
  src/components/common/Buttons/LinkButton/LinkButtonStyle.js
  src/constants/COLORS.js
  src/pages/PostCreatingPage/PostCreatingPage.jsx
  src/pages/PostCreatingPage/PostCreatingPageStyle.js
Labels: FEATURE

#36 colors.js 파일 오류 수정
  src/Router.jsx
  src/components/BackgroundSelector/BackgroundSelector.jsx
  src/constants/COLORS.js
Labels: FIX

#37 잘못 만든 Button파일 삭제 후 AddButton.jsx를 Button으로 이동
  src/assets/icons/plus.svg
  src/components/Badge/Badge.jsx
  src/components/Badge/BadgeStyle.js
  src/components/PostCard/AddPostCard.jsx
  src/components/common/Buttons/AddButton/AddButton.jsx
  src/components/common/Buttons/AddButton/AddButtonStyle.js
  src/pages/RecipientsPage/RecipientsPage.jsx
Labels: FIX

#38 버튼 컴포넌트 수정
  src/components/common/Buttons/Button/Button.jsx
  src/components/common/Buttons/Button/ButtonStyle.js
  src/components/common/Buttons/LinkButton/LinkButton.jsx
  src/components/common/Buttons/LinkButton/LinkButtonStyle.js
  src/constants/buttonSize.js
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomepageStyle.js
  src/pages/PostCreatingPage/PostCreatingPage.jsx
Labels: FEATURE

#40 PostCreatingPage 기능 구현 완료
  src/Router.jsx
  src/apis/recipientRollingPaperApi.js
  src/components/BackgroundTypeSelectButton/BackgroundTypeSelectButtonStyle.js
  src/components/common/Buttons/Button/Button.jsx
  src/pages/PostCreatingPage/PostCreatingPage.jsx
Labels: FEATURE

#41 카드 모달 컴포넌트 추가
  src/components/CardModal/CardModal.jsx
  src/components/CardModal/CardModalStyle.js
  src/components/PostCard/PostCard.jsx
  src/pages/RecipientsPage/RecipientsPage.jsx
  src/pages/RecipientsPage/RecipientsPageStyle.js
Labels: FEATURE

#39 Aje/reactions
  src/apis/recipientRollingPaperApi.js
  src/components/EmojiPicker/EmojiPicker.jsx
  src/components/ProfileCircles/ProfileCircles.jsx
  src/components/ProfileCircles/ProfileCirclesStyle.js
  src/components/ReactionDropdown/ReactionDropdown.jsx
  src/components/ServiceHeader/ServiceHeader.jsx
  src/components/ShareButton/ShareButton.jsx
  src/components/WritersList/WritersList.jsx
  src/components/WritersList/WritersListStyle.js
  src/hooks/usePostData.js
Labels: FEATURE

#45 버튼 컴포넌트 리팩토링 진행
  src/components/common/Buttons/Button/ButtonStyle.js
  src/constants/buttonSize.js
Labels: REFACTOR

#46 fix: 이모지 등록에 성공했을 때만 reload
  src/components/EmojiPicker/EmojiPicker.jsx
  src/hooks/usePostData.js
Labels: FIX

#43 PostWritingPage 기능 구현 완료
  src/Router.jsx
  src/apis/getProfileImages.js
  src/apis/recipientRollingPaperApi.js
  src/assets/icons/arrowTop.svg
  src/assets/icons/basicProfile.svg
  src/components/Input/Input.jsx
  src/components/Input/InputStyle.js
  src/components/SelectionDropdown/SelectionDropdown.jsx
  src/components/SelectionDropdown/SelectionDropdownStyle.js
  src/components/TextEditor/TextEditor.jsx
  src/components/TextEditor/TextEditorStyle.js
  src/constants/fonts.js
  src/constants/relationships.js
  src/constants/viewportSize.js
  src/pages/PostCreatingPage/PostCreatingPage.jsx
  src/pages/PostWritingPage/PostWritingPage.jsx
  src/pages/PostWritingPage/PostWritingPageStyle.js
Labels: FEATURE

#47 롤링페이퍼 및 카드에대한 폰트 추가
  public/index.html
  src/FontStyle.js
  src/components/CardModal/CardModal.jsx
  src/components/CardModal/CardModalStyle.js
  src/components/PostCard/PostCard.jsx
  src/components/PostCard/PostCardStyle.js
Labels: FEATURE

#51 refetch 추가 및 package-lock 추가
  package-lock.json
  src/hooks/useFetchData.js
Labels: FEATURE, REFACTOR

#44 PostCard 무한 스크롤 구현 및 AddPostCard 활성화
  src/apis/recipientRollingPaperApi.js
  src/components/PostCard/AddPostCard.jsx
  src/components/PostCard/PostCard.jsx
  src/components/PostCard/PostCardStyle.js
  src/components/common/Buttons/AddButton/AddButtonStyle.js
  src/components/common/Header/HeaderStyle.js
  src/hooks/useIntersectionObserver.js
  src/pages/RecipientsPage/RecipientsPage.jsx
  src/pages/RecipientsPage/RecipientsPageStyle.js
Labels: FEATURE

#52 PostWritingPage 에러 메세지 기능 수정 & PostCreatingPage 오류 수정
  src/components/TextEditor/TextEditor.jsx
  src/components/TextEditor/TextEditorStyle.js
  src/pages/PostCreatingPage/PostCreatingPage.jsx
  src/pages/PostCreatingPage/PostCreatingPageStyle.js
Labels: FIX

#28 목록 페이지 생성
  src/Router.jsx
  src/apis/recipientRollingPaperApi.js
  src/assets/Icons/mainIcon.svg
  src/assets/icons/arrowLeft.svg
  src/assets/icons/arrowRight.svg
  src/assets/icons/mainIcon.svg
  src/assets/images/cardPattern1.svg
  src/assets/images/cardPattern2.svg
  src/assets/images/cardPattern3.svg
  src/assets/images/cardPattern4.svg
  src/components/ListPage/ListCard/ListCard.jsx
  src/components/ListPage/ListCard/ListCardStyle.js
  src/components/ListPage/ListCardContent/ListCardContent.jsx
  src/components/ListPage/ListCardContent/ListCardContentStyle.js
  src/components/ProfileCircles/ProfileCircles.jsx
  src/components/TopReactions/TopReactionsStyle.js
  src/components/common/Buttons/ArrowButton/ArrowButton.jsx
  src/components/common/Buttons/ArrowButton/ArrowButtonStyle.js
  src/components/common/Header/Header.jsx
  src/hooks/useFetchRecipient.js
  src/pages/ListPage/ListPage.jsx
  src/pages/ListPage/ListPageStyle.js
Labels: FEATURE

#53 모든 모바일 영역에서 Header가 보이지 않는 문제 수정
  src/components/common/Header/HeaderStyle.js
  src/pages/RecipientsPage/RecipientsPageStyle.js
Labels: FIX

#54 버튼 컴포넌트 폰트 사이즈가 없을 시 기본값 설정
  src/components/common/Buttons/Button/ButtonStyle.js
Labels: REFACTOR

#58 헤더 box-shadow 설정
  src/components/common/Header/HeaderStyle.js
Labels: FEATURE

#55 fix: HorizontalBar 100vh->100%로 수정
  src/components/ServiceHeader/ServiceHeaderStyle.js
Labels: FIX

#57 `/post` & `/post/{id}/message` 반응형 추가
  src/components/BackgroundSelector/BackgroundSelector.jsx
  src/components/BackgroundSelector/BackgroundSelectorStyle.js
  src/components/TextEditor/TextEditor.jsx
  src/pages/PostCreatingPage/PostCreatingPage.jsx
  src/pages/PostCreatingPage/PostCreatingPageStyle.js
  src/pages/PostWritingPage/PostWritingPage.jsx
Labels: FIX

#61 fix: 대문자 아이콘 폴더 삭제
  src/assets/Icons/mainIcon.svg
Labels: FIX

#60 ListPage 관련 반응형 미디어 쿼리 부분 수정 및 오타 수정
  src/components/ListPage/ListCard/ListCardStyle.js
  src/components/ListPage/ListCardContent/ListCardContent.jsx
  src/pages/ListPage/ListPage.jsx
  src/pages/ListPage/ListPageStyle.js
Labels: REFACTOR

#59 ListCard 너비 수정 & 반응형 폰트 사이즈 수정
  src/components/ListPage/ListCard/ListCardStyle.js
  src/components/ListPage/ListCardContent/ListCardContentStyle.js
  src/pages/ListPage/ListPageStyle.js
Labels: REFACTOR

#63 PostCard 삭제 버튼 기능 구현
  src/apis/recipientRollingPaperApi.js
  src/components/PostCard/PostCard.jsx
  src/components/ShareButton/ShareButton.jsx
  src/components/common/Toast/ToastStyle.js
  src/pages/RecipientsPage/RecipientsPage.jsx
  src/pages/RecipientsPage/RecipientsPageStyle.js
Labels: FEATURE

#62 Quill delta HTML 변환 기능 추가
  package.json
  src/components/InnerHtml/InnerHtml.jsx
  src/components/InnerHtml/InnerHtmlAttributes.js
  src/components/InnerHtml/InnerHtmlStyle.js
  src/components/PostCard/PostCard.jsx
  src/components/PostCard/PostCardStyle.js
  src/components/TextEditor/TextEditor.jsx
Labels: FEATURE

#64 메인 페이지 이미지 구체적인 네이밍, 반응형 미디어 쿼리 적용, 시맨틱 태그
  src/components/MainContent/MainContent.jsx
  src/components/MainContent/MainContentStyle.js
  src/pages/HomePage/HomepageStyle.js
Labels: REFACTOR

#67 `/post/{id}` 오류 수정
  src/components/InnerHtml/InnerHtml.jsx
  src/components/InnerHtml/InnerHtmlAttributes.js
Labels: FIX

#71 특정 `/post/{id}`로 넘어가지지 않는 오류 수정
  src/components/InnerHtml/InnerHtml.jsx
  src/components/PostCard/PostCard.jsx
  src/components/PostCard/PostCardStyle.js
Labels: FIX

#73 목록 페이지 화살표 버튼, 상수 관련 리팩토링 진행
  src/components/ListPage/ListCardContent/ListCardContent.jsx
  src/components/common/Buttons/ArrowButton/ArrowButton.jsx
Labels: REFACTOR

#79 window.innerWidth 잘못 측정되는 현상 해결
  src/components/ListPage/ListCardContent/ListCardContent.jsx
Labels: FIX

#75 `/post` 화면 여백 오류 수정
  src/components/BackgroundTypeSelectButton/BackgroundTypeSelectButtonStyle.js
  src/components/PostCard/PostCardStyle.js
  src/pages/PostCreatingPage/PostCreatingPage.jsx
  src/pages/PostCreatingPage/PostCreatingPageStyle.js
  src/pages/PostWritingPage/PostWritingPageStyle.js
Labels: FIX

#77 하단에 스크롤이 있다는 것을 보여주기 위한 scroll arrow 추가 / 카드 개수가 적을 때 배경화면 잘리는 현상 수정
  src/GlobalStyle.js
  src/components/PostCard/PostCard.jsx
  src/components/PostCard/PostCardStyle.js
  src/components/ServiceHeader/ServiceHeader.jsx
  src/components/ServiceHeader/ServiceHeaderStyle.js
  src/pages/RecipientsPage/RecipientsPage.jsx
  src/pages/RecipientsPage/RecipientsPageStyle.js
Labels: FEATURE, REFACTOR

#78 `/post/{id}/message` skeleton UI 추가
  package.json
  src/pages/PostWritingPage/PostWritingPage.jsx
  src/pages/PostWritingPage/PostWritingPageStyle.js
Labels: FEATURE

#80 모달에서 글이 제대로 출력되지 않는 오류 수정
  src/components/CardModal/CardModal.jsx
  src/components/CardModal/CardModalStyle.js
  src/components/InnerHtml/InnerHtml.jsx
  src/components/InnerHtml/InnerHtmlStyle.js
  src/components/PostCard/PostCard.jsx
Labels: FIX

#72 이모지 클릭시 reload -> rerender 수정
  src/components/EmojiPicker/EmojiPicker.jsx
  src/components/ReactionDropdown/ReactionDropdown.jsx
  src/components/ServiceHeader/ServiceHeader.jsx
Labels: REFACTOR

#81 Layout으로 잡힌 Header가 모든 /post페이지의 모바일 화면에서 보이지 않도록 수정
  src/AppLayout.jsx
Labels: REFACTOR

#82 png 파일 webp로 변경
  src/assets/images/error.png
  src/assets/images/error.webp
  src/assets/images/profileImg.jpg
  src/pages/ErrorPage/ErrorPage.jsx
Labels: REFACTOR

#74 메인페이지 이미지 리사이징 후 적용
  src/assets/images/mainImg1.png
  src/assets/images/mainImg1.webp
  src/assets/images/mainImg2.png
  src/assets/images/mainImg2.webp
  src/components/MainContent/MainContent.jsx
  src/components/MainContent/MainContentStyle.js
Labels: REFACTOR

#86 viewport 모든 숫자 constant로 변경
  src/components/CardModal/CardModalStyle.js
  src/components/EmojiBadge/EmojiBadgeStyle.js
  src/components/EmojiPicker/EmojiPickerStyle.js
  src/components/InnerHtml/InnerHtmlStyle.js
  src/components/PostCard/PostCard.jsx
  src/components/PostCard/PostCardStyle.js
  src/components/ReactionDropdown/ReactionDropdownStyle.js
  src/components/ServiceHeader/ServiceHeaderStyle.js
  src/components/ShareButton/ShareButtonStyle.js
  src/components/WritersList/WritersListStyle.js
  src/components/common/Header/HeaderStyle.js
  src/components/common/Toast/ToastStyle.js
  src/constants/viewportSize.js
  src/pages/RecipientsPage/RecipientsPage.jsx
  src/pages/RecipientsPage/RecipientsPageStyle.js
Labels: REFACTOR

#88 `/post/{id}/message` 스켈레톤 오류 및 key 관련 Lint 경고 수정
  src/pages/PostWritingPage/PostWritingPage.jsx
  src/pages/PostWritingPage/PostWritingPageStyle.js
Labels: FIX

#89 getFontStyle 대소문자 수정
  src/FontStyle.js
  src/components/CardModal/CardModalStyle.js
  src/components/InnerHtml/InnerHtmlStyle.js
Labels: REFACTOR

#91 import구문 정리를 위한 lint 설정 & px과 rem 단위 통일 & onDelete 오류 수정
  .eslintrc.json
  src/components/BackgroundSelector/BackgroundSelectorStyle.js
  src/components/BackgroundTypeSelectButton/BackgroundTypeSelectButtonStyle.js
  src/components/Badge/BadgeStyle.js
  src/components/CardModal/CardModalStyle.js
  src/components/EmojiBadge/EmojiBadgeStyle.js
  src/components/EmojiPicker/EmojiPickerStyle.js
  src/components/InnerHtml/InnerHtmlStyle.js
  src/components/Input/InputStyle.js
  src/components/ListPage/ListCard/ListCardStyle.js
  src/components/MainContent/MainContentStyle.js
  src/components/PostCard/PostCardStyle.js
  src/components/ProfileCircles/ProfileCirclesStyle.js
  src/components/ReactionDropdown/ReactionDropdownStyle.js
  src/components/SelectionDropdown/SelectionDropdownStyle.js
  src/components/ShareButton/ShareButtonStyle.js
  src/components/common/Buttons/AddButton/AddButtonStyle.js
  src/components/common/Buttons/ArrowButton/ArrowButtonStyle.js
  src/components/common/Buttons/Button/ButtonStyle.js
  src/components/common/Toast/ToastStyle.js
  src/pages/ListPage/ListPageStyle.js
  src/pages/PostWritingPage/PostWritingPageStyle.js
  src/pages/RecipientsPage/RecipientsPage.jsx
  src/pages/RecipientsPage/RecipientsPageStyle.js
Labels: REFACTOR, FIX

#93 README 작성
  README.md
Labels: FEATURE

#97 무한 스크롤 영상 올라가지 않는 현상 해결
  README.md
Labels: FIX

#96 반응형 크기 수정
  src/components/ListPage/ListCardContent/ListCardContent.jsx
Labels: REFACTOR

#95 `/post/{id}` card 데이터 줄바꿈 수정
  src/components/InnerHtml/InnerHtmlStyle.js
Labels: REFACTOR
